version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agile-ready-app
    ports:
      - "3000:3000"
    # Membaca nilai dari file .env di lokal Anda, atau menggunakan nilai default di bawahnya
    env_file:
      - .env
    environment:
      # Jika Neo4j berjalan di localhost mesin host (bukan Docker), gunakan host.docker.internal
      # Alihkan NEO4J_URI ke nilai ini jika Anda tidak menggunakan URL cloud
      - NEO4J_URI=${NEO4J_URI:-bolt://host.docker.internal:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-solidaritastimur}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-x12bgjydyjhjcghgc}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
    # Konfigurasi ini memungkinkan container berkomunikasi dengan localhost sistem operasi Anda
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
